[package]
name = "container"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
nix = { version = "0.30", features = ["sched", "process", "hostname", "mount", "fs"] }
libc = "0.2"
cidr = "0.3.2"
